apiVersion: v1
kind: ServiceAccount
metadata:
  name: constraint-enforcement-sa
  namespace: constraint-enforcement
  labels:
    app: constraint-enforcement-engine
automountServiceAccountToken: false
